name: Create Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    # We need to use an old runner for Xcode 11.7
    # TODO: Use a matrix instead
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        path: orion
    - name: Set Up Dependencies
      id: setup
      run: |
        brew install ldid make fakeroot
        echo "THEOS=${GITHUB_WORKSPACE}/theos" >> "${GITHUB_ENV}"
        echo "PATH=/usr/local/opt/make/libexec/gnubin:${PATH}" >> "${GITHUB_ENV}"
        echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
    - name: Install Theos
      uses: actions/checkout@v2
      with:
        repository: theos/theos
        ref: 153c50c49dbbac0b47b87f9480d8d2c5d6d2ace1
        path: theos
        submodules: recursive
    - name: Build Release
      run: |
        cd orion
        # Orion doesnt build with 12.5 atm due to a compiler bug (SR-14535)
        DEVELOPER_DIR=/Applications/Xcode_12.4.app/Contents/Developer make clean package FINALPACKAGE=1
        DEVELOPER_DIR=/Applications/Xcode_12.4.app/Contents/Developer make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
        DEVELOPER_DIR=/Applications/Xcode_11.7.app/Contents/Developer make clean package FINALPACKAGE=1
    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ github.workspace }}/orion/packages/*
        tag_name: ${{ github.ref }}
        name: ${{ steps.setup.outputs.version }}
        body: ''
        draft: true
        prerelease: false
